---
- name: Configure Ubuntu VM for E-Commerce Application
  hosts: all
  become: true

  vars:
    ssh_port: 222
    node_exporter_version: "1.7.0"
    deploy_user: vagrant

# Roles - order matters!
  roles:
    - role: docker
      tags: docker
    - role: node_exporter
      tags: node_exporter
    - role: sshd
      tags: sshd
    - role: ufw
      tags: ufw
    - role: gitlab_runner
      tags: gitlab_runner
